export const BASE_URL = import.meta.env.VITE_MODE === "Production" ? import.meta.env.VITE_APP_API_URL : import.meta.env.VITE_LOCALHOST_URL ;
export const IMAGE_URL = import.meta.env.VITE_MODE === "Production" ? import.meta.env.VITE_APP_IMAGE_URL : import.meta.env.VITE_APPLOCAL_IMAGE_URL ;

export const subCasteOptions = [
  { label: 'Anavil', value: 'Anavil' },
  { label: 'Anavil Desai', value: 'Anavil Desai' },
  { label: 'Audichya', value: 'Audichya' },
  { label: 'Bagra', value: 'Bagra' },
  { label: 'Baragoan', value: 'Baragoan' },
  { label: 'Bardai', value: 'Bardai' },
  { label: 'Barendra', value: 'Barendra' },
  { label: 'Bhargav', value: 'Bhargav' },
  { label: 'Bhatt', value: 'Bhatt' },
  { label: 'Bhojak', value: 'Bhojak' },
  { label: 'Bhumihar', value: 'Bhumihar' },
  { label: 'Chaubisa', value: 'Chaubisa' },
  { label: 'Bairagi', value: 'Bairagi' },
  { label: 'Dakaut', value: 'Dakaut' },
  { label: 'Dadhich', value: 'Dadhich' },
  { label: 'Daivadnya', value: 'Daivadnya' },
  { label: 'Danva', value: 'Danva' },
  { label: 'Deshastha', value: 'Deshastha' },
  { label: 'Devrukhe', value: 'Devrukhe' },
  { label: 'Dhiman', value: 'Dhiman' },
  { label: 'Dravida', value: 'Dravida' },
  { label: 'Embrandiri', value: 'Embrandiri' },
  { label: 'Garhwali', value: 'Garhwali' },
  { label: 'Gaur', value: 'Gaur' },
  { label: 'Gurjar Gaur', value: 'Gurjar Gaur' },
  { label: 'Aadi Gaur', value: 'Aadi Gaur' },
  { label: 'Shri Gaur', value: 'Shri Gaur' },
  { label: 'Goswami', value: 'Goswami' },
  { label: 'Gurukkal', value: 'Gurukkal' },
  { label: 'Halua', value: 'Halua' },
  { label: 'Hoysala', value: 'Hoysala' },
  { label: 'Havyaku', value: 'Havyaku' },
  { label: 'Iyengar', value: 'Iyengar' },
  { label: 'Iyer', value: 'Iyer' },
  { label: 'Jangid', value: 'Jangid' },
  { label: 'Jangra', value: 'Jangra' },
  { label: 'Jhadua', value: 'Jhadua' },
  { label: 'Jijhotia', value: 'Jijhotia' },
  { label: 'Jyotish', value: 'Jyotish' },
  { label: 'Kanyakubj', value: 'Kanyakubj' },
  { label: 'Karhade', value: 'Karhade' },
  { label: 'Khandelwal', value: 'Khandelwal' },
  { label: 'Kokanastha', value: 'Kokanastha' },
  { label: 'Kota', value: 'Kota' },
  { label: 'Koteshwara', value: 'Koteshwara' },
  { label: 'Kulin', value: 'Kulin' },
  { label: 'Kumaoni', value: 'Kumaoni' },
  { label: 'Madhwa', value: 'Madhwa' },
  { label: 'Maithil', value: 'Maithil' },
  { label: 'Malviya Brahmin', value: 'Malviya Brahmin' },
  { label: 'Modh', value: 'Modh' },
  { label: 'Mohyal', value: 'Mohyal' },
  { label: 'Nagar', value: 'Nagar' },
  { label: 'Namboodiri', value: 'Namboodiri' },
  { label: 'Narmadiya', value: 'Narmadiya' },
  { label: 'Niyogi', value: 'Niyogi' },
  { label: 'Paliwal', value: 'Paliwal' },
  { label: 'Panda', value: 'Panda' },
  { label: 'Panicker', value: 'Panicker' },
  { label: 'Pushkarna', value: 'Pushkarna' },
  { label: 'Rajgor', value: 'Rajgor' },
  { label: 'Khadayata', value: 'Khadayata' },
  { label: 'Pandit', value: 'Pandit' },
  { label: 'Pareek', value: 'Pareek' },
  { label: 'Patnaick', value: 'Patnaick' },
  { label: 'Rarhi', value: 'Rarhi' },
  { label: 'Rigvedi', value: 'Rigvedi' },
  { label: 'Rudraj', value: 'Rudraj' },
  { label: 'Sakal Dwipi', value: 'Sakal Dwipi' },
  { label: 'Sanketi', value: 'Sanketi' },
  { label: 'Sarua', value: 'Sarua' },
  { label: 'Shivalli', value: 'Shivalli' },
  { label: 'Shri Mali', value: 'Shri Mali' },
  { label: 'Shukla Yajurvedi', value: 'Shukla Yajurvedi' },
  { label: 'Smartha', value: 'Smartha' },
  { label: 'Sikhwal', value: 'Sikhwal' },
  { label: 'SriVaishnava', value: 'SriVaishnava' },
  { label: 'Stanika', value: 'Stanika' },
  { label: 'Swarnakar Brahmin', value: 'Swarnakar Brahmin' },
  { label: 'Sanadya', value: 'Sanadya' },
  { label: 'Saraswat', value: 'Saraswat' },
  { label: 'Saryuparin', value: 'Saryuparin' },
  { label: 'Tyagi', value: 'Tyagi' },
  { label: 'Tapodhan', value: 'Tapodhan' },
  { label: 'Vaidiki', value: 'Vaidiki' },
  { label: 'Valam', value: 'Valam' },
  { label: 'Vaikhanasa', value: 'Vaikhanasa' },
  { label: 'Velanadu', value: 'Velanadu' },
  { label: 'Vyas', value: 'Vyas' },
  { label: 'Viswabrahmin', value: 'Viswabrahmin' },
  { label: 'Zalora', value: 'Zalora' },
  { label: 'Other', value: 'Other' },
];